#!/usr/bin/env sh

# load scripting additions (optional)
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
yabai -m signal --add event=window_focused action="sketchybar --trigger window_focus"
yabai -m signal --add event=display_added action="sleep 2 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=display_removed action="sleep 1 && $HOME/.config/yabai/create_spaces.sh"
yabai -m signal --add event=window_created action="sketchybar --trigger windows_on_spaces"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger windows_on_spaces"

$HOME/.config/yabai/create_spaces.sh
# default layout (can be bsp, stack or float)
yabai -m config layout bsp

# new window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

# padding set to 12px
yabai -m config top_padding 10
yabai -m config bottom_padding 12
yabai -m config left_padding 12
yabai -m config right_padding 12
yabai -m config window_gap 12

# -- mouse settings --

# center mouse on window with focus
yabai -m config mouse_follows_focus on

# modifier for clicking and dragging with mouse
yabai -m config mouse_modifier alt
# set modifier + left-click drag to move window
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window
yabai -m config mouse_action2 resize

# when window is dropped in center of another window, swap them (on edges it will split it)

# disable specific apps
yabai -m rule --add app="^iPhone Mirroring$" manage=off
yabai -m rule --add app="^Stickies$" manage=off
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^QuickTime Player$" manage=off
yabai -m rule --add app="^GitHub Desktop$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Finder" manage=off
yabai -m rule --add app="^Screen Studio" manage=off
yabai -m rule --add app="^FaceTime" manage=off
yabai -m rule --add app="^ExpressVPN" manage=off
yabai -m rule --add app="^Digital Color Meter" manage=off
yabai -m rule --add app="^ColorSlurp$" manage=off
yabai -m rule --add app="^Calendar$" manage=off

# Sketchybar settings
yabai -m config external_bar all:$(sketchybar --query bar | jq .height):0
